addons:
  apt:
    packages:
    - jq
script:
- "./get-keys.sh jackrayner"
- "./push.sh"
env:
  global:
    secure: LZ4wXuAyJjmGwyXbJIhoYF/RYSPwW9KkRdwVbcgSYzpq+LiHmP1yiwZJ7HWf5T8qXipgCv2K8D3+8suatOPDfXDp35SPJL7li1e5dvnz3pHVgGe7d3O+qtGLN0m4JxnEKGfr+vyoIwWMiMU8dXLoZ3ARsaSnuBRf6nakikkD+T4+5oQBmiP7h7Thv336xsW43Si88PaAAwVOaV+qXNeaCJ9t6Fmb6+QSicJeUC8pXNH+R5ndfXlubjg5VWdFmuaEoNjvU88UOiToqQQEbf5XFATjUtq1DeChWQgqRkCC5M5A4eCNBRkSzPJbKtiewhKAKuP1GNnuZK5R/N4GUzvncak3TDqSgNjGum5I4944/6t1bQu/X+/Kw1UDfSo8sOJf3cO/4G+RvmCWTp8iD1FdQ+q4EyYhIuQ1J5h9z/LKfeA5Gx20O1BX/02YsmX1MqzUllM92idL8pXkQ5IcG0swdJv1VPSqXovc3RIp4hjsPzBhlsBiIMOjSCb0tiWHlo/JOZsF0aI+1l87KP4dLekWtX/chuJU873suqRuX21+7e1XznGJHhwefER/aiWdcOQ75UvepjP4OYEjFU9n2U6AUJ82Z1I6wSXHp4J5CuxbIj7Z0TCk+Hrlc3vRTgqvEbJrsg27ptyH7sDpWwRtVQP5dK4qB1QFmgHFsEKLBaW/8MU=
